[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "puzzle1"
path = "src/puzzle1/main.rs"

[[bin]]
name = "puzzle2"
path = "src/puzzle2/main.rs"

[[bin]]
name = "puzzle3"
path = "src/puzzle3/main.rs"

[dependencies]
bitset = "0.1.2"
