[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "puzzle1"
path = "src/puzzle1/main.rs"

[[bin]]
name = "puzzle2"
path = "src/puzzle2/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]